"""
Predefined poster templates for Pixolab.
Each template defines: layout type, required images, input fields, design parameters.
"""

TEMPLATES = [
    {
        "id": "tech_product_launch",
        "name": "Tech Product Launch",
        "description": "Dark cinematic poster with ambassador, floating product and feature highlights",
        "long_description": "Perfect for smartphones, gadgets and tech products. Dramatic dark background, person on the left, product floating on the right, with a feature highlights bar at the bottom.",
        "category": "Technology",
        "tag": "Most Popular",
        "style": "product_poster",
        "dimensions": [1080, 1350],
        "preview_colors": ["#050618", "#1a1a3e", "#0a2f6e"],
        "accent_hex": "#00c8ff",
        "required_images": [
            {"key": "person", "label": "Brand Ambassador", "sublabel": "Person holding or presenting the product", "optional": True},
            {"key": "product", "label": "Product Shot", "sublabel": "Phone, device or tech product"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "Samsung Galaxy", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Main Headline", "placeholder": "THE FUTURE IN YOUR HAND", "required": True, "icon": "Zap", "group": "main"},
            {"key": "subheadline", "label": "Tagline", "placeholder": "NEXT IS NOW", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "feature1", "label": "Feature 1", "placeholder": "Pro-Grade Camera", "required": False, "icon": "Camera", "group": "features"},
            {"key": "feature2", "label": "Feature 2", "placeholder": "Powerful Performance", "required": False, "icon": "Cpu", "group": "features"},
            {"key": "feature3", "label": "Feature 3", "placeholder": "All-Day Battery", "required": False, "icon": "Battery", "group": "features"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Order Now", "required": False, "icon": "ChevronRight", "group": "main"},
        ],
        "layout": "tech_split",
    },
    {
        "id": "elegance_power",
        "name": "Elegance Meets Power",
        "description": "Premium editorial with centered product showcase and ambassador portrait",
        "long_description": "Sophisticated dark editorial style. Product displayed prominently with ambassador in a powerful side-by-side composition. Ideal for luxury and lifestyle brands.",
        "category": "Fashion & Lifestyle",
        "tag": "Premium",
        "style": "brand_ambassador",
        "dimensions": [1080, 1350],
        "preview_colors": ["#111111", "#1e1e1e", "#2d2d2d"],
        "accent_hex": "#4da6ff",
        "required_images": [
            {"key": "person", "label": "Ambassador / Model", "sublabel": "Professional portrait or half-body", "optional": True},
            {"key": "product", "label": "Hero Product", "sublabel": "Product on pedestal or clean background"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "Luxe Series", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Campaign Headline", "placeholder": "ELEGANCE MEETS POWER", "required": True, "icon": "Sparkles", "group": "main"},
            {"key": "subheadline", "label": "Descriptor", "placeholder": "Built for those who demand more.", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Discover More", "required": False, "icon": "ChevronRight", "group": "main"},
        ],
        "layout": "elegance_centered",
    },
    {
        "id": "performance_action",
        "name": "Built to Perform",
        "description": "Bold action-ready poster with dramatic lighting and feature icon bar",
        "long_description": "High-energy layout for performance products. Dynamic deep background, feature icon bar at bottom, bold power headline and optional bottom tagline.",
        "category": "Sports & Tech",
        "tag": "Bold",
        "style": "product_poster",
        "dimensions": [1080, 1350],
        "preview_colors": ["#080010", "#1a0a3e", "#2a0a5e"],
        "accent_hex": "#00aaff",
        "required_images": [
            {"key": "person", "label": "Brand Ambassador", "sublabel": "Action or power pose", "optional": True},
            {"key": "product", "label": "Product", "sublabel": "Device, gadget or hero product"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "Galaxy Pro", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Power Headline", "placeholder": "BUILT TO PERFORM", "required": True, "icon": "Zap", "group": "main"},
            {"key": "subheadline", "label": "Sub-Tagline", "placeholder": "BEYOND LIMITS", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "feature1", "label": "Feature 1", "placeholder": "Water & Dust Resistant", "required": False, "icon": "Shield", "group": "features"},
            {"key": "feature2", "label": "Feature 2", "placeholder": "Ultra-Fast 5G", "required": False, "icon": "Signal", "group": "features"},
            {"key": "feature3", "label": "Feature 3", "placeholder": "Immersive Display", "required": False, "icon": "Monitor", "group": "features"},
            {"key": "bottom_tagline", "label": "Bottom Tagline", "placeholder": "POWER. STYLE. INNOVATION.", "required": False, "icon": "Star", "group": "extra"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Get Yours", "required": False, "icon": "ChevronRight", "group": "main"},
        ],
        "layout": "performance_action",
    },
    {
        "id": "beauty_glow",
        "name": "Beauty & Glow",
        "description": "Soft luminous aesthetic for skincare, cosmetics and beauty products",
        "long_description": "Warm, glowing backdrop with soft lighting perfect for beauty brands. Features benefit badges and a luxurious warm aesthetic.",
        "category": "Beauty",
        "tag": "Trending",
        "style": "instagram_ad",
        "dimensions": [1080, 1080],
        "preview_colors": ["#2d0835", "#7a1a5e", "#c4306e"],
        "accent_hex": "#ffaacc",
        "required_images": [
            {"key": "person", "label": "Model", "sublabel": "Portrait or close-up shot", "optional": True},
            {"key": "product", "label": "Beauty Product", "sublabel": "Serum, cream or cosmetics item"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "GlowLab", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Headline", "placeholder": "Glow Naturally", "required": True, "icon": "Sparkles", "group": "main"},
            {"key": "subheadline", "label": "Benefit Line", "placeholder": "24-hour radiance, visible results", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "benefit1", "label": "Key Benefit 1", "placeholder": "Brightening", "required": False, "icon": "Star", "group": "features"},
            {"key": "benefit2", "label": "Key Benefit 2", "placeholder": "Anti-Aging", "required": False, "icon": "Star", "group": "features"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Shop Now", "required": False, "icon": "ChevronRight", "group": "main"},
        ],
        "layout": "beauty_glow",
    },
    {
        "id": "sports_energy",
        "name": "Sports & Energy",
        "description": "High-impact bold layout for sports brands, energy drinks and fitness products",
        "long_description": "Explosive energy with bold gradient background, athlete in action and powerful typography. Great for YouTube thumbnails and social campaigns.",
        "category": "Sports",
        "tag": "High Energy",
        "style": "youtube_thumbnail",
        "dimensions": [1280, 720],
        "preview_colors": ["#0d0a1e", "#3d0a6e", "#8b1a4e"],
        "accent_hex": "#ffe632",
        "required_images": [
            {"key": "person", "label": "Athlete / Influencer", "sublabel": "Action shot or power pose", "optional": True},
            {"key": "product", "label": "Product", "sublabel": "Sports product, supplement or equipment"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "BeastMode", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Power Headline", "placeholder": "DOMINATE THE GAME", "required": True, "icon": "Zap", "group": "main"},
            {"key": "subheadline", "label": "Battle Cry", "placeholder": "NO LIMITS. NO EXCUSES.", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Get Yours", "required": False, "icon": "ChevronRight", "group": "main"},
        ],
        "layout": "sports_dynamic",
    },
    {
        "id": "corporate_pro",
        "name": "Corporate Professional",
        "description": "Clean authoritative layout for business campaigns and executive branding",
        "long_description": "Professional and trustworthy. Perfect for B2B campaigns, LinkedIn ads and corporate marketing. Clean lines, trust-building color palette.",
        "category": "Business",
        "tag": "B2B",
        "style": "linkedin_post",
        "dimensions": [1200, 627],
        "preview_colors": ["#051227", "#0c4e8b", "#1a7fc1"],
        "accent_hex": "#52c5ff",
        "required_images": [
            {"key": "person", "label": "Executive / Professional", "sublabel": "Business portrait or headshot", "optional": True},
            {"key": "product", "label": "Product / Service Visual", "sublabel": "Product, logo or service graphic"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Company / Brand", "placeholder": "Acme Corp", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Campaign Message", "placeholder": "Innovation Drives Us", "required": True, "icon": "Zap", "group": "main"},
            {"key": "subheadline", "label": "Supporting Line", "placeholder": "Trusted by 10,000+ businesses", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Learn More", "required": False, "icon": "ChevronRight", "group": "main"},
        ],
        "layout": "corporate_split",
    },
    {
        "id": "premium_hero_product",
        "name": "Premium Hero",
        "description": "Product takes center stage right, ambassador faded left, bold left-side text panel",
        "long_description": "The product is the undisputed hero. Placed large on the right with a cinematic blue glow. Ambassador subtly fades into the dark left background. Text panel: brand chip, headline, tagline and CTA — all on the left. Feature bar at the bottom.",
        "category": "Technology",
        "tag": "New",
        "style": "product_poster",
        "dimensions": [1080, 1350],
        "preview_colors": ["#030512", "#060c2a", "#041644"],
        "accent_hex": "#00b4ff",
        "required_images": [
            {"key": "person", "label": "Brand Ambassador", "sublabel": "Full body or portrait — faded into background", "optional": True},
            {"key": "product", "label": "Hero Product", "sublabel": "Phone, device or product — will be placed large on right"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "Samsung Galaxy", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Main Headline", "placeholder": "THE FUTURE IN YOUR HAND", "required": True, "icon": "Zap", "group": "main"},
            {"key": "subheadline", "label": "Tagline", "placeholder": "NEXT IS NOW", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Order Now", "required": False, "icon": "ChevronRight", "group": "main"},
            {"key": "feature1", "label": "Feature 1", "placeholder": "Pro-Grade Camera", "required": False, "icon": "Camera", "group": "features"},
            {"key": "feature2", "label": "Feature 2", "placeholder": "Powerful Performance", "required": False, "icon": "Cpu", "group": "features"},
            {"key": "feature3", "label": "Feature 3", "placeholder": "All-Day Battery", "required": False, "icon": "Battery", "group": "features"},
        ],
        "layout": "premium_hero",
    },
    {
        "id": "influencer_split_poster",
        "name": "Influencer Split",
        "description": "Circular influencer portrait left, product right, brand top-center, CTA bottom-center",
        "long_description": "Headshots are automatically cropped into a glowing circular portrait on the left. Product floats on the right. Brand name centered at the top. Headline, tagline and CTA are centered at the bottom over a dark gradient scrim.",
        "category": "Fashion & Lifestyle",
        "tag": "Trending",
        "style": "product_poster",
        "dimensions": [1080, 1350],
        "preview_colors": ["#040510", "#070e2c", "#051640"],
        "accent_hex": "#00b4ff",
        "required_images": [
            {"key": "person", "label": "Influencer / Model", "sublabel": "Headshot or portrait — auto-cropped to circle", "optional": True},
            {"key": "product", "label": "Featured Product", "sublabel": "Product placed on the right side"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "Apple", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Campaign Headline", "placeholder": "DESIGNED FOR YOU", "required": True, "icon": "Zap", "group": "main"},
            {"key": "subheadline", "label": "Tagline", "placeholder": "Where style meets performance.", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Shop Now", "required": False, "icon": "ChevronRight", "group": "main"},
            {"key": "feature1", "label": "Feature 1", "placeholder": "Ultra Display", "required": False, "icon": "Monitor", "group": "features"},
            {"key": "feature2", "label": "Feature 2", "placeholder": "Pro Camera", "required": False, "icon": "Camera", "group": "features"},
            {"key": "feature3", "label": "Feature 3", "placeholder": "All-Day Battery", "required": False, "icon": "Battery", "group": "features"},
        ],
        "layout": "influencer_split",
    },
    {
        "id": "futuristic_launch",
        "name": "Futuristic Launch",
        "description": "Concentric energy rings frame a centered floating product — sci-fi launch aesthetic",
        "long_description": "Dark cinematic background with glowing concentric rings drawn around the product. The ambassador is rendered as an ultra-faint background element. Product floats centered in the rings. All text is centered — brand top, headline below, CTA below product, feature bar at the bottom.",
        "category": "Technology",
        "tag": "Futuristic",
        "style": "product_poster",
        "dimensions": [1080, 1350],
        "preview_colors": ["#02030e", "#040822", "#051038"],
        "accent_hex": "#00bfff",
        "required_images": [
            {"key": "person", "label": "Ambassador / Model", "sublabel": "Used as a ghost background element", "optional": True},
            {"key": "product", "label": "Launch Product", "sublabel": "Product centered inside the rings"},
        ],
        "fields": [
            {"key": "brand_name", "label": "Brand Name", "placeholder": "OnePlus", "required": True, "icon": "BadgeCheck", "group": "main"},
            {"key": "headline", "label": "Launch Headline", "placeholder": "THE FUTURE IS NOW", "required": True, "icon": "Zap", "group": "main"},
            {"key": "subheadline", "label": "Tagline", "placeholder": "Redefining what's possible.", "required": False, "icon": "Lightbulb", "group": "main"},
            {"key": "cta", "label": "Call to Action", "placeholder": "Pre-Order Now", "required": False, "icon": "ChevronRight", "group": "main"},
            {"key": "feature1", "label": "Feature 1", "placeholder": "Next-Gen Chip", "required": False, "icon": "Cpu", "group": "features"},
            {"key": "feature2", "label": "Feature 2", "placeholder": "200MP Camera", "required": False, "icon": "Camera", "group": "features"},
            {"key": "feature3", "label": "Feature 3", "placeholder": "5000mAh Battery", "required": False, "icon": "Battery", "group": "features"},
        ],
        "layout": "futuristic_launch",
    },
]

TEMPLATE_MAP = {t["id"]: t for t in TEMPLATES}
